/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuggestRouteImport } from './routes/suggest'
import { Route as NrvrAdminRouteImport } from './routes/nrvr-admin'
import { Route as IndexRouteImport } from './routes/index'

const SuggestRoute = SuggestRouteImport.update({
  id: '/suggest',
  path: '/suggest',
  getParentRoute: () => rootRouteImport,
} as any)
const NrvrAdminRoute = NrvrAdminRouteImport.update({
  id: '/nrvr-admin',
  path: '/nrvr-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/nrvr-admin': typeof NrvrAdminRoute
  '/suggest': typeof SuggestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/nrvr-admin': typeof NrvrAdminRoute
  '/suggest': typeof SuggestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/nrvr-admin': typeof NrvrAdminRoute
  '/suggest': typeof SuggestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/nrvr-admin' | '/suggest'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/nrvr-admin' | '/suggest'
  id: '__root__' | '/' | '/nrvr-admin' | '/suggest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NrvrAdminRoute: typeof NrvrAdminRoute
  SuggestRoute: typeof SuggestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suggest': {
      id: '/suggest'
      path: '/suggest'
      fullPath: '/suggest'
      preLoaderRoute: typeof SuggestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nrvr-admin': {
      id: '/nrvr-admin'
      path: '/nrvr-admin'
      fullPath: '/nrvr-admin'
      preLoaderRoute: typeof NrvrAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NrvrAdminRoute: NrvrAdminRoute,
  SuggestRoute: SuggestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
